services:
  test-backend-3:
    build:
      context: .
      target: production
    image: test-backend-3
    container_name: test-backend-3
    depends_on:
      - test-backend-3-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: test-backend-3-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  test-backend-3-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: test-backend-3
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
